language: php

php:
  - '7.4'
services:
  - docker

before_install:
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

env:
  global:
    - COMPOSE_DOCKER_CLI_BUILD=1
    - DOCKER_BUILDKIT=1

script:
  - docker-compose build
  - docker-compose up -d
  - until docker-compose exec php bin/console doctrine:query:sql "SELECT 1"  ; do  sleep 1 ; done
  - docker-compose exec php composer tests
  - docker-compose rm --stop --force -v
  - sudo rm -rf data/.postgres
