language: php

php:
  - '7.4'

before_install: cd backend
install:
  - composer install
services:
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
before_script:
  - psql -c "CREATE ROLE app_test LOGIN  PASSWORD 'app_test'" -U postgres
  - psql -c 'CREATE DATABASE app_test OWNER app_test' -U postgres

env:
  global:
    - TEST_DATABASE_URL="pgsql://app_test:app_test@localhost:5432/app_test?serverVersion=12&charset=utf8"

script:
  - composer auto-scripts
  - composer tests
