language: php

php:
  - '7.4'

before_install:
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo apt-get -y purge docker docker-engine docker.io containerd runc
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce docker-ce-cli containerd.io

env:
  global:
    - COMPOSE_DOCKER_CLI_BUILD=1
    - DOCKER_BUILDKIT=1

script:
  - id
  - cat /etc/group
  - docker-compose build
  - docker-compose up -d
  - until docker-compose exec php bin/console doctrine:query:sql "SELECT 1"  ; do  sleep 1 ; done
  - docker-compose exec php composer tests
  - docker-compose rm --stop --force -v
  - sudo rm -rf data/.postgres
