language: php

php:
  - '7.4'

before_install:
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo apt-get -y purge docker docker-engine docker.io containerd runc
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce docker-ce-cli containerd.io

script:
  - docker-compose build
  - docker-compose up -d
  - |
    function waitUntil() {
      local retry=0
      until "$@"  > /dev/null 2>&1 ; do
        sleep 1
        ((retry=retry+1))
        if [ $retry > 10 ] ; then
          break
        fi
      done

     $@
    }
    waitUntil docker-compose exec php bin/console doctrine:query:sql "SELECT 1"
  - docker-compose exec php composer tests
  - docker-compose rm --stop --force -v
